Repository GDSC-JSCOE/Competitive-Programming, pull requests merged in 2022-09, with the labels that each got.

#1 Update README.md
  README.md
Labels: hacktoberfest-accepted

#2 q1 and q2 solved
  Beginner.txt
Labels: hacktoberfest-accepted

#4 q3 solved
  Beginner.txt
Labels: hacktoberfest-accepted

#5 added a solution on line 60 ,question 11
  Beginner.txt
Labels: hacktoberfest-accepted

#6 answered question 10
  Beginner.txt
Labels: hacktoberfest-accepted

#7 q4 solved
  Beginner.txt
Labels: hacktoberfest-accepted

#8 Update Beginner.txt
  Beginner.txt
Labels: hacktoberfest-accepted

#9 Update Beginner.txt
  Beginner.txt
Labels: hacktoberfest-accepted

#11 q6 solved
  Beginner.txt
Labels: hacktoberfest-accepted

#16 Update Beginner.txt
  Beginner.txt
Labels: hacktoberfest-accepted

#15 Update Beginner.txt
  Beginner.txt
Labels: hacktoberfest-accepted

#17 Update Beginner.txt
  Beginner.txt
Labels: hacktoberfest-accepted

#18 Update Advance.txt
  Advance.txt
Labels: hacktoberfest-accepted

#19 Update Intermediate.txt
  Intermediate.txt
Labels: hacktoberfest-accepted

#20 Update Intermediate.txt
  Intermediate.txt
Labels: hacktoberfest-accepted

#21 Update Beginner.txt
  Beginner.txt
Labels: hacktoberfest-accepted

#22 Q3 solved
  Beginner.txt
Labels: hacktoberfest-accepted

#26 12solved
  Beginner.txt
Labels: hacktoberfest-accepted

#24 Update Beginner.txt
  Beginner.txt
Labels: hacktoberfest-accepted

#28 Update Beginner.txt
  Beginner.txt
Labels: hacktoberfest-accepted

#29 Update Beginner.txt
  Beginner.txt
Labels: invalid

#25 Updated Fibonacci
  Advance.txt
Labels: hacktoberfest-accepted

#27 add name
  Beginner.txt
Labels: invalid

#31 13solved
  Beginner.txt
Labels: hacktoberfest-accepted

#32 Update Beginner.txt
  Beginner.txt
Labels: invalid, spam

#33 Younus
  Intermediate.txt
Labels: hacktoberfest-accepted

#36 added 18 c program
  Beginner.txt
Labels: hacktoberfest-accepted

#35 15solved
  Beginner.txt
Labels: hacktoberfest-accepted

#34 Update Advance.txt
  Advance.txt
Labels: hacktoberfest-accepted

#23 Update Beginner.txt
  Beginner.txt
Labels: hacktoberfest-accepted

#39 added solution for ques8
  Intermediate.txt
Labels: hacktoberfest-accepted

#41 9solved
  Beginner.txt
Labels: hacktoberfest-accepted

#43 6solved
  Beginner.txt
Labels: hacktoberfest-accepted

#44 hactoberfest
  Intermediate.txt
Labels: hacktoberfest-accepted

#40 hactoberfest
  Intermediate.txt
Labels: hacktoberfest-accepted

#45 3solved
  Intermediate.txt
Labels: hacktoberfest-accepted

#46 hactoberfest
  Intermediate.txt
Labels: hacktoberfest-accepted

#48 added solution for ques21
  Beginner.txt
Labels: hacktoberfest-accepted

#49 3solved
  Beginner.txt
Labels: hacktoberfest-accepted

#53 string palindrome problem in cpp
  Intermediate.txt
Labels: hacktoberfest-accepted

#56 solved Q 21
  Beginner.txt
Labels: hacktoberfest-accepted

#58 Update Intermediate.txt
  Intermediate.txt
Labels: hacktoberfest-accepted

#60 Intermediate.txt
  Intermediate.txt
Labels: hacktoberfest-accepted

#57 updated.txt
  Beginner.txt
Labels: hacktoberfest-accepted

#61 solved Q no 9
  Intermediate.txt
Labels: hacktoberfest-accepted

#62 hactoberfest
  Beginner.txt
Labels: hacktoberfest-accepted

#59 binary search code in java
  Intermediate.txt
Labels: hacktoberfest-accepted

#63 hactoberfest
  Beginner.txt
Labels: hacktoberfest-accepted

#65 hactoberfest
  Beginner.txt
Labels: hacktoberfest-accepted

#66 Update Intermediate.txt
  Intermediate.txt
Labels: hacktoberfest-accepted

#67 hactoberfest
  Beginner.txt
Labels: hacktoberfest-accepted

#68 7.rotate array soln
  Intermediate.txt
Labels: hacktoberfest-accepted

#69 solved Q no 13
  Intermediate.txt
Labels: hacktoberfest-accepted

#71 compiupdated.txt
  Intermediate.txt
Labels: hacktoberfest-accepted

#72 committed!!
  Beginner.txt
Labels: hacktoberfest-accepted

#75 Mahesh0911 patch 4
  Intermediate.txt
Labels: hacktoberfest-accepted

#77 q3. palindrome of string
  Intermediate.txt
Labels: hacktoberfest-accepted

#78 3question
  Intermediate.txt
Labels: hacktoberfest-accepted

#79 question 17 AP
  Intermediate.txt
Labels: hacktoberfest-accepted

#80 Solved Q no 1 and 3 using python
  Beginner.txt
Labels: hacktoberfest-accepted

#81 11solved
  Intermediate.txt
Labels: hacktoberfest-accepted

#83 solved Q no 3 using python
  Intermediate.txt
Labels: hacktoberfest-accepted

#84 23solved
  Intermediate.txt
Labels: hacktoberfest-accepted

#85 Update Intermediate.txt
  Intermediate.txt
Labels: hacktoberfest-accepted

#86 24solved
  Intermediate.txt
Labels: hacktoberfest-accepted

#87 Update Intermediate.txt
  Intermediate.txt
Labels: hacktoberfest-accepted

#88 23 solved
  Intermediate.txt
Labels: hacktoberfest-accepted

#89 hactoberfest
  Intermediate.txt
Labels: hacktoberfest-accepted

#90 Added GCD Problem
  Beginner.txt
Labels: hacktoberfest-accepted

#91 Designing of a simple calculator using java
  Intermediate.txt
Labels: hacktoberfest-accepted

#92 19solved
  Intermediate.txt
Labels: hacktoberfest-accepted

#93 Added solution to new question in intermediate.txt
  Intermediate.txt
Labels: hacktoberfest-accepted

#95 Added binary to Decimal Conversion
  Beginner.txt
Labels: hacktoberfest-accepted

#96 added Printing pattern question
  Intermediate.txt
Labels: hacktoberfest-accepted

#97 Update Beginner.txt
  Beginner.txt
Labels: hacktoberfest-accepted

#99 question 15 solved
  Intermediate.txt
Labels: hacktoberfest-accepted

#101 Update Beginner.txt
  Beginner.txt
Labels: hacktoberfest-accepted

#103 Update Intermediate.txt
  Intermediate.txt
Labels: hacktoberfest-accepted

#104 C++ program The number diamond pattern is a diamond pattern made up of numbers.
  Intermediate.txt
Labels: hacktoberfest-accepted

#105 Update Intermediate.txt
  Intermediate.txt
Labels: hacktoberfest-accepted

#106 Update Advance.txt
  Advance.txt
Labels: hacktoberfest-accepted

#107 Update Advance.txt
  Advance.txt
Labels: hacktoberfest-accepted

#108 Update Intermediate.txt
  Intermediate.txt
Labels: hacktoberfest-accepted

#109 Update Intermediate.txt
  Intermediate.txt
Labels: hacktoberfest-accepted

#110 update.txt
  Beginner.txt
Labels: hacktoberfest-accepted

#111 Update Advance.txt
  Advance.txt
Labels: hacktoberfest-accepted

#112 corrected the name string
  Beginner.txt
Labels: hacktoberfest-accepted

#113 Update Advance.txt
  Advance.txt
Labels: hacktoberfest-accepted

#118 Update Advance.txt added 1st answer
  Advance.txt
Labels: hacktoberfest-accepted

#119 17 solved
  Beginner.txt
Labels: hacktoberfest-accepted

#115 Update Intermediate.txt
  Intermediate.txt
Labels: invalid, spam

#116 Update Advance.txt
  Advance.txt
Labels: hacktoberfest-accepted

#117 Update Advance.txt
  Advance.txt
Labels: hacktoberfest-accepted

#121 Beginner ques 5 solved in c++
  Beginner.txt
Labels: hacktoberfest-accepted

#124 Update Advance.txt
  Advance.txt
Labels: hacktoberfest-accepted

#126 Update Intermediate.txt
  Intermediate.txt
Labels: hacktoberfest-accepted
